{% set opencl_devel_ver="1.2.0-2018090742" %}
{% set opencl_devel_sha256="369d1aec83a18eec2665faed59bde266e54daef21bd6b1150d9dfb054b7d201d" %}

package:
    name: roctools
    version:  {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - path: ../..
  - fn: rocm-opencl-devel-{{ opencl_devel_ver }}.x86_64.rpm
    url: http://repo.radeon.com/rocm/yum/rpm/rocm-opencl-devel-{{ opencl_devel_ver }}.x86_64.rpm
    folder: opencl_tmp
    sha256: {{ opencl_devel_sha256 }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }} # [unix]
    - {{ compiler('cxx') }} # [unix]
    - cmake>=2.8
    - xz
    - zlib
    - bzip2
    - libarchive
    - llvmdev_amdgcn=roc_1.9.x
    # gtest is used in the test binaries
    - gtest

  host:
    - zlib # for llvm binary tooling that is copied in

test:
  commands:
    # The librocmlite.so DSO is tested at compile time

    # Check llvm binaries actually run
    - opt --help | grep amdgpu
    - llc --help | grep amdgpu
    - llvm-link --help
    - ld.lld --help

about:
    home: https://github.com/numba/roctools
    license: BSD
    summary: A shared library that wraps LLVM for code
             generation for devices with Radeon Open Compute support.
    license_file: LICENSE
